import os
## ADD CONFIG
maxthreads = 5
hmm_threshold = 0.0001

operon_maper_dir = 'operonmapper_output'
profiles_dir = 'hmms'
scripts_dir = 'scripts'
hmm_res_dir = 'hmm_res'
logs_dir = 'logs'
# define dirs to make
os.makedirs(hmm_res_dir, exist_ok=True)
os.makedirs(logs_dir, exist_ok=True)


# rule all:
#     input:
        
# rule gene_boundaries:
#     input:
#         pass
#     output:
#         pass
#     conda:
#         "envs/prodigal.yaml"
#     shell:
#         pass

# rule annotation:
#     input:
#         pass
#     output:
#         pass
#     conda:
#         "envs/bakta.yaml"
#     shell:
#         pass

rule operon_mapping:
    input:
        "example/operonmapper.fasta"
    output:
        "operonmapper_output/list_of_operons"
    conda:
        "envs/operonmapper.yaml"
    shell:
        # Here should juggle also between `python operonmapper.py start ...`
        # Now choosing `continue` for fast testing process
        "python operonmapper.py continue 3735332 -o operonmapper_output"

rule find_o_antigen_orfs:
    input:
        faa = os.path.join(operon_maper_dir, 'predicted_protein_sequences')
    output:
        txt = os.path.join(hmm_res_dir, 'o_ant_products.txt')
    params:
        hmms_path = 'o_antigen.hmm',
        hmm_thres = hmm_threshold
    conda:
        'envs/hmmer.yml'
    threads:
        maxthreads
    log: stdout = "logs/hmmsearch.stdout", stderr = "logs/hmmsearch.stderr"
    shell:
        """
        ( hmmsearch --noali --notextw -E {params.hmm_thres} --domE {params.hmm_thres} \
        --tblout {output} {params.hmms_path} {input.faa}
        ) > {log.stdout} 2> {log.stderr} 
        """


rule parse_hmm_res:
    input:
        txt = os.path.join(hmm_res_dir, 'o_ant_products.txt'),
    output:
        tsv=os.path.join(hmm_res_dir, 'o_ant_products.tsv')
    params:
        scripts_path=os.path.join(scripts_dir, 'parsehmm.py'),
        decoder_path=os.path.join(profiles_dir, 'keggs.tsv')
    threads:
        1
    shell:
        """
        python3 {params.scripts_path} {input.txt} {params.decoder_path} {output.tsv}
        """

# rule operon_filtering:
#     input:
#         pass
#     output:
#         pass
#     conda:
#         "envs/hmm.yaml"
#     shell:
#         pass